### ISSUE TITLE
Question: how is the target-plugin being used?

### ISSUE THREAD

**Issue by novemberkilo** [lukesthl/digital-break-app#2]
Hello - thanks so much for making this project and making it public. I am using it as a way to understand how to add `AppIntents` to an expo project and I have a question. Essentially, how is the target-plugin being used by the `DigitalBreak` app? I see that it sets an apple-team-id in the `plugins` section of `app.config.ts` and I can see that this is used by the `target-plugin` but I'm struggling to understand the full purpose of the plugin and its usage. 

Any tips to help will be greatly appreciated. And yes, I am using the app, and benefiting from the many digital breaks that it is serving up :) Thank you.  

Edit: I see that the plugin appears as this PR https://github.com/EvanBacon/expo-apple-targets/pull/9 and the README of the `expo-apple-targets` project helps. Please feel free to close this question/issue if you would rather not duplicate information from there. I'm still not clear on how things integrate (and how to use the plugin in my own project) but perhaps all the information is here and I just need to spend some more time with the code.

**Comment by lukesthl** [comment]
hey navin,
sorry i haven't seen your issue until now.
I'll do my best to explain, although I haven't worked on an Expo app with this specific setup since creating this one. Understanding how the Expo Config Plugins work took me a while, especially since I wasn't familiar with the iOS build process. Additionally, there isn't much information available about Expo plugins in combination with AppIntent.

To clarify, the target-plugin is imported into the app via `app.plugin.js`. This plugin reads from the [target folders in the intents directory](https://github.com/lukesthl/digital-break-app/tree/main/apps/expo/targets/intents). These folders each contains an `expo-target.config.js`, which can be configured for different purposes such as widgets, watch apps, or, in this case, AppIntents. These configurations modify the XCode Project file ([project.pbxproj](https://github.com/lukesthl/digital-break-app/tree/main/apps/expo/ios/digitalbreak.xcodeproj/project.pbxproj)) accordingly.

The changes you see in my PR adjust the setup so that every .swift file in `/targets/intents` is recognized. This is all done during the Expo prebuild phase. After this setup, the AppIntent files should be linked to the app and function as described in the Apple documentation.

hope i could help you, if you have any specific questions feel free to ask them.

**Comment by novemberkilo** [comment]
Thanks so much for the reply Luke. Much appreciated.
